# Generated by Django 5.1.1 on 2025-03-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_gender_alter_userrecord_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('NON_BINARY', 'non_binary')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='gender',
            field=models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('NON_BINARY', 'non_binary')], max_length=10),
        ),
    ]
