# Generated by Django 5.1.1 on 2025-03-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='video_url',
            field=models.URLField(max_length=2000),
        ),
    ]
