# Generated by Django 5.1.1 on 2024-10-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedproducts',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='likedproducts',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='savedproducts',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='savedproducts',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='wishlistedproducts',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='wishlistedproducts',
            old_name='user_id',
            new_name='user',
        ),
    ]
