# Generated by Django 5.1.1 on 2024-11-04 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('activity', '0002_rename_product_id_likedproducts_product_and_more'),
        ('feed', '0007_alter_product_brand_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedproducts',
            name='product',
        ),
        migrations.RemoveField(
            model_name='savedproducts',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlistedproducts',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlistedproducts',
            name='user',
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('save', 'SAVE'), ('like', 'LIKE'), ('wishlist', 'WISHLIST')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'unique_together': {('user', 'product', 'action')},
            },
        ),
        migrations.DeleteModel(
            name='LikedProducts',
        ),
        migrations.DeleteModel(
            name='SavedProducts',
        ),
        migrations.DeleteModel(
            name='WishlistedProducts',
        ),
    ]
