# Generated by Django 5.1.1 on 2024-11-05 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('activity', '0003_remove_savedproducts_product_and_more'),
        ('feed', '0007_alter_product_brand_product_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useractivity',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='feed.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='account.user'),
        ),
        migrations.AddConstraint(
            model_name='useractivity',
            constraint=models.UniqueConstraint(fields=('user', 'post', 'action'), name='unique_user_post_action'),
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='product',
        ),
    ]
