# Generated by Django 5.1.1 on 2024-10-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_remove_post_updated_at_post_description_post_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.CharField(blank=True, max_length=255, null=True, default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
