# Generated by Django 5.1.1 on 2024-10-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_product_discount_price_product_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
