# Generated by Django 5.1.1 on 2024-10-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_alter_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
