# Generated by Django 5.1.1 on 2024-11-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_alter_product_brand_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_embeddings',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='text_embeddings',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
