# Generated by Django 5.1.1 on 2024-11-07 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_rename_product_description_product_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_embeddings',
            new_name='image_embedding',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='text_embeddings',
            new_name='text_embedding',
        ),
    ]
