# Generated by Django 5.1.1 on 2024-11-07 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_rename_image_embeddings_product_image_embedding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_embedding',
        ),
        migrations.RemoveField(
            model_name='product',
            name='text_embedding',
        ),
        migrations.CreateModel(
            name='ProductEmbeddings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_embedding', models.JSONField(blank=True, null=True)),
                ('image_embedding', models.JSONField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='feed.product')),
            ],
        ),
    ]
