# Generated by Django 5.1.1 on 2025-02-21 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_product_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('image_url', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('brand', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Curation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curation_type', models.CharField(choices=[('SINGLE', 'Single'), ('MULTI', 'Multi'), ('MULTI_INSPIRATION', 'Multi Inspiration')], max_length=20)),
                ('curation_image', models.URLField()),
                ('parent_curation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_curations', to='feed.curation')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('curation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='feed.curation')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_items', to='feed.component')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_components', to='feed.item')),
            ],
        ),
    ]
