# Generated by Django 5.1.1 on 2025-02-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_item_marketplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
