# Generated by Django 5.1.1 on 2025-03-07 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_alter_item_image_url_alter_item_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyntraProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('subcategory', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(max_length=1024)),
                ('secondary_images', models.JSONField(blank=True, null=True)),
                ('product_link', models.URLField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('marketplace', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyntraProductEmbeddings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_embedding', models.JSONField(blank=True, null=True)),
                ('image_embedding', models.JSONField(blank=True, null=True)),
                ('fclip_text_embedding', models.JSONField(blank=True, null=True)),
                ('myntra_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='feed.myntraproducts')),
            ],
        ),
    ]
