# Generated by Django 5.1.1 on 2025-03-17 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_myntraproducts_myntraproductembeddings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyntraProductTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('fit', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
                ('print', models.CharField(blank=True, max_length=255, null=True)),
                ('sleeve', models.CharField(blank=True, max_length=255, null=True)),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('neckline', models.CharField(blank=True, max_length=255, null=True)),
                ('design', models.CharField(blank=True, max_length=255, null=True)),
                ('myntra_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='feed.myntraproducts')),
            ],
        ),
    ]
