# Generated by Django 5.1.1 on 2025-04-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0018_myntraproducttags'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderId', models.CharField(max_length=255)),
                ('media_url', models.URLField(max_length=1024)),
                ('media_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimilarProductResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1024)),
                ('similar_products', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
