# Generated by Django 5.1.1 on 2025-04-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0019_remove_componentitem_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curation',
            name='related_curations',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='feed.curation'),
        ),
    ]
