# Generated by Django 5.1.1 on 2025-04-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0020_similarproductresults_vision_result_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimilarProductResults',
        ),
        migrations.AddField(
            model_name='detectedobjectproducts',
            name='is_whole_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detectedobjectproducts',
            name='vision_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='detectedobjectproducts',
            index=models.Index(fields=['is_whole_image'], name='feed_detect_is_whol_e70eac_idx'),
        ),
    ]
